---
- name: Provision ESP-IDF, ESP-Matter, and Android build prerequisites
  hosts: all
  gather_facts: true

  vars_prompt:
    - name: esp_install_dir
      prompt: "Install directory for ESP-IDF/ESP-Matter"
      default: "~/.esp"
      private: false
    - name: chip_install_dir
      prompt: "Install directory for connectedhomeip (upstream)"
      default: "~/connectedhomeip"
      private: false

  pre_tasks:
    - name: Expand install directory
      ansible.builtin.set_fact:
        esp_install_dir_expanded: "{{ (ansible_facts['env']['HOME'] if base == '~' else (ansible_facts['env']['HOME'] ~ base[1:]) if base.startswith('~/') else base) }}"
      tags: ["always"]
      vars:
        base: "{{ esp_install_dir | default('~/.esp') }}"
    - name: Expand connectedhomeip directory
      ansible.builtin.set_fact:
        chip_install_dir_expanded: "{{ (ansible_facts['env']['HOME'] if base == '~' else (ansible_facts['env']['HOME'] ~ base[1:]) if base.startswith('~/') else base) }}"
      tags: ["always"]
      vars:
        base: "{{ chip_install_dir | default('~/connectedhomeip') }}"

  roles:
    - role: preflight
      tags: ["preflight"]
    - role: esp_idf
      tags: ["esp_idf"]
    - role: esp_matter
      tags: ["esp_matter"]
    - role: chip_upstream
      tags: ["chip_upstream"]
    - role: android_matter
      tags: ["android_matter"]
      when: android_matter_setup_enabled | bool
